#!/usr/bin/env python3
"""Render the preregistered 50-seed component-ablation table from evidence."""

from __future__ import annotations

import argparse
from decimal import Decimal, ROUND_HALF_UP
import hashlib
import json
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
REGISTRY = REPO_ROOT / "docs/gdsq_vla_iclr2027/experiment_registry.json"
TEX = REPO_ROOT / "docs/gdsq_vla_iclr2027/tables/component_ablation.tex"
AUDIT = REPO_ROOT / "docs/gdsq_vla_iclr2027/tables/component_ablation.audit.json"
DEV4 = {"CoffeeSetupMug", "OpenCabinet", "OpenStandMixerHead", "PickPlaceDrawerToCounter"}
ROWS = [
    ("CKA only", "full_gdsq_vs_cka_only"),
    ("CS only", "full_gdsq_vs_cs_only"),
    ("Uniform weights ($w_i=1$)", "full_gdsq_vs_weights_uniform"),
    ("No guards", "full_gdsq_vs_no_guards"),
    ("No adjudication", "full_gdsq_vs_no_functional_adjudication"),
]
PENDING = r"\textit{pending}"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def resolve(value: str) -> Path:
    path = Path(value)
    return path.resolve() if path.is_absolute() else (REPO_ROOT / path).resolve()


def verified(record: dict[str, Any], label: str) -> tuple[Path, dict[str, Any]]:
    path = resolve(record["path"])
    require(path.is_file(), f"missing {label}: {path}")
    require(sha256_file(path) == record["sha256"], f"{label} SHA drift")
    return path, json.loads(path.read_text(encoding="utf-8"))


def pct(value: float, digits: str = "0.1") -> str:
    return str(
        Decimal(str(100.0 * value)).quantize(Decimal(digits), rounding=ROUND_HALF_UP)
    )


def pvalue(value: float) -> str:
    return str(Decimal(str(value)).quantize(Decimal("0.001"), rounding=ROUND_HALF_UP))


def render() -> tuple[str, dict[str, Any]]:
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    static_path, static = verified(
        registry["experiments"]["gr00t_static_official50"]["summary"],
        "static GR00T summary",
    )
    atomic_tasks = set(static["task_sets"]["atomic_seen"])
    baseline_rates = {
        task: float(value)
        for task, value in static["configs"]["cscka_final"]["per_task"].items()
        if task in atomic_tasks and task not in DEV4
    }
    require(len(baseline_rates) == 14, "Primary14 baseline scope drift")
    baseline = sum(baseline_rates.values()) / len(baseline_rates)
    record = registry["experiments"]["gr00t_component_ablation50"]
    statistics_path = None
    statistics = None
    if record.get("status") == "complete" and record.get("statistics"):
        statistics_path, statistics = verified(record["statistics"], "ablation statistics")
        require(statistics.get("complete") is True, "ablation statistics incomplete")
        require(len(statistics.get("contrasts", {})) == 5, "five contrasts required")

    lines = [
        "% AUTO-GENERATED by scripts/tools/render_gdsq_component_ablation.py; DO NOT EDIT.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Preregistered GR00T component ablations on Primary-14 with 50 paired seeds per task. $\Delta$ is full GDSQ-VLA minus the ablation; $p$ is Holm-adjusted over five contrasts. Crashes, NaNs, and out-of-range actions in the no-guards arm count as failures.}",
        r"\label{tab:component_ablation_50}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{1.5pt}",
        r"\renewcommand{\arraystretch}{1.05}",
        r"\begin{tabular}{@{}lrrrr@{}}",
        r"\toprule",
        r"Config. & SR (\%) & $\Delta$ [95\% CI] & \shortstack{Holm\\$p$} & \shortstack{Fail.\\(\%)} \\",
        r"\midrule",
        f"Full GDSQ-VLA & {pct(baseline)} & -- & -- & --" + r" \\",
    ]
    rendered_rows = []
    for label, contrast_name in ROWS:
        if statistics is None:
            values = [PENDING] * 4
        else:
            row = statistics["contrasts"][contrast_name]
            ci = row["task_cluster_ci95"]
            values = [
                pct(float(row["ablation_task_macro_sr"])),
                f"{pct(float(row['delta_full_minus_ablation']))} "
                f"[{pct(float(ci[0]))},{pct(float(ci[1]))}]",
                pvalue(float(row["holm_adjusted_p"])),
                pct(float(row["formal_failure_rate"])),
            ]
        lines.append(f"{label} & " + " & ".join(values) + r" \\")
        rendered_rows.append({"label": label, "contrast": contrast_name, "values": values})
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    audit = {
        "schema_version": 1,
        "kind": "gdsq_vla_component_ablation_table",
        "registry": {"path": str(REGISTRY.relative_to(REPO_ROOT)), "sha256": sha256_file(REGISTRY)},
        "static_summary": {"path": str(static_path.relative_to(REPO_ROOT)), "sha256": sha256_file(static_path)},
        "ablation_statistics": (
            {"path": str(statistics_path.relative_to(REPO_ROOT)), "sha256": sha256_file(statistics_path)}
            if statistics_path
            else None
        ),
        "status": record.get("status"),
        "rows": rendered_rows,
        "pending_cells_claim_disabled": statistics is None,
    }
    return "\n".join(lines), audit


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    tex, audit = render()
    audit_text = json.dumps(audit, indent=2, sort_keys=True) + "\n"
    if args.check:
        require(TEX.read_text(encoding="utf-8") == tex, "component-ablation TeX is stale")
        require(AUDIT.read_text(encoding="utf-8") == audit_text, "component-ablation audit is stale")
        print(f"component-ablation sources verified: {TEX}")
        return
    TEX.write_text(tex, encoding="utf-8")
    AUDIT.write_text(audit_text, encoding="utf-8")
    print(f"component ablation rendered: {TEX}")


if __name__ == "__main__":
    main()
